# Generated by Django 6.1.2 on 2026-10-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=60)),
                ('zona', models.CharField(max_length=60)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=120)),
                ('categoria', models.CharField(max_length=40)),
                ('registrado', models.DateField(auto_now_add=True)),
                ('monto', models.PositiveIntegerField()),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='presupuesto.mision')),
            ],
        ),
    ]
